[package]
name = "MiCompositionScale2"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
datetime = "0.5.2"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
json = "0.12.4"
reqwest = { version = "0.12.7", features = ["blocking"] }
tokio = {version = "1.39.3", features = ["full"]}

